import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile,readdir,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {createRequire} from 'node:module';
import {relative,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import {prepareStaticPrefetch} from '../scripts/prepare-static-prefetch.mjs';
import {staticPrefetchRoutes,prefetchAssetDirectory} from '../scripts/static-prefetch-routes.mjs';
const require=createRequire(import.meta.url),picomatch=require('next/dist/compiled/picomatch');
const source=await readFile(new URL('../next.config.ts',import.meta.url),'utf8');
const versionSource=await readFile(new URL('../app/generated/build-version.ts',import.meta.url),'utf8');
const versionUrl='data:text/javascript;base64,'+Buffer.from(ts.transpileModule(versionSource,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
const emitted=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText
 .replace("'./app/generated/build-version'",JSON.stringify(versionUrl))
 .replace("'./scripts/static-prefetch-routes.mjs'",JSON.stringify(new URL('../scripts/static-prefetch-routes.mjs',import.meta.url).href));
const {default:config}=await import('data:text/javascript;base64,'+Buffer.from(emitted).toString('base64'));
const contentRoot=fileURLToPath(new URL('../content/courses/',import.meta.url));
const files=(await readdir(contentRoot,{recursive:true,withFileTypes:true})).filter(entry=>entry.isFile()).map(entry=>'./content/courses/'+relative(contentRoot,join(entry.parentPath,entry.name)).replaceAll('\\','/'));
const matchesFile=(pattern,file)=>picomatch(pattern.replace(/^\.\//,''))(file.replace(/^\.\//,''));

test('EdgeOne include patterns never schedule parallel copies to the same content path',()=>{
 // EdgeOne flattens route-specific globs before parallel cp, without deduplication.
 // Replay its config reader against our real source, then resolve content paths.
 const body=source.match(/outputFileTracingIncludes\s*:\s*\{([\s\S]*?)(?=\n\s*\}[,;\s]*\n|\n\s*\}\s*[,\n])/)[1];
 const pairs=[...body.matchAll(/['"]([^'"]+)['"]\s*:\s*\[([\s\S]*?)\]/g)];
 const patterns=pairs.flatMap(pair=>[...pair[2].matchAll(/['"]([^'"]+)['"]/g)].map(match=>match[1]));
 assert.ok(patterns.length);
 const scheduled=patterns.flatMap(pattern=>files.filter(file=>matchesFile(pattern,file)));
 assert.equal(scheduled.length,new Set(scheduled).size,'duplicate destinations cause EdgeOne cp/unlink races');
 assert.deepEqual([...new Set(scheduled)].sort(),files.sort(),'all original course content remains packaged');
});

test('server routes retain all course content in Next file traces',()=>{
 for(const route of ['/courses','/courses/STAT-201','/courses/STAT-201/lesson-1','/courses/STAT-201/assessments/case-study','/courses/STAT-201/review','/api/courses/STAT-201/progress']){
  const patterns=Object.entries(config.outputFileTracingIncludes).filter(([glob])=>picomatch(glob)(route)).flatMap(([,patterns])=>patterns);
  assert.ok(patterns.length,route);
  for(const file of files)assert.ok(patterns.some(pattern=>matchesFile(pattern,file)),route+' missing '+file);
 }
});

test('segment rewrites cover only public static pages and reject traversal paths',async()=>{
 const rules=(await config.rewrites()).beforeFiles;
 assert.deepEqual(rules.map(r=>r.source),staticPrefetchRoutes);
 assert.ok(rules.every(r=>!r.source.startsWith('/api/')));
 assert.equal(rules.some(r=>r.source==='/'),false,'cookie-dependent homepage must stay dynamic');
 const requestPattern=new RegExp('^(?:'+rules[0].has[1].value+')$');
 assert.ok(requestPattern.test('/papers/__PAGE__'));
 assert.ok(requestPattern.test('/_tree'));
 assert.equal(requestPattern.test('/../../api/profile'),false);
 assert.ok((await config.headers()).every(rule=>rule.headers.some(h=>h.key==='X-Nextjs-Postponed'&&h.value==='2')));
});

test('build publishes unchanged validated segment files under its own identity',async context=>{
 const directory=await mkdtemp(join(tmpdir(),'acaora-segments-'));
 context.after(()=>rm(directory,{recursive:true,force:true}));
 const buildId='a'.repeat(40);const routes={};
 await writeFile(join(directory,'BUILD_ID'),buildId);
 for(const route of staticPrefetchRoutes) {
  routes[route]={initialRevalidateSeconds:false};
  const folder=join(directory,'server/app',(route==='/'?'index':route.slice(1))+'.segments');
  await mkdir(join(folder,'child'),{recursive:true});
  await writeFile(join(folder,'_tree.segment.rsc'),'0:'+JSON.stringify({tree:{name:''},buildId}));
  await writeFile(join(folder,'child','__PAGE__.segment.rsc'),'framework-generated bytes');
 }
 await writeFile(join(directory,'prerender-manifest.json'),JSON.stringify({routes}));
 const result=await prepareStaticPrefetch({buildDirectory:directory});
 assert.equal(result.files,staticPrefetchRoutes.length*2);
 assert.equal(await readFile(join(directory,'static',buildId,prefetchAssetDirectory,'papers','child','__PAGE__.rsc'),'utf8'),'framework-generated bytes');
 await writeFile(join(directory,'server/app/papers.segments/_tree.segment.rsc'),'0:'+JSON.stringify({tree:{},buildId:'b'.repeat(40)}));
 await assert.rejects(prepareStaticPrefetch({buildDirectory:directory}),/PREFETCH_TREE_INVALID: \/papers/);
 routes['/papers']={initialRevalidateSeconds:0};
 await writeFile(join(directory,'prerender-manifest.json'),JSON.stringify({routes}));
 await assert.rejects(prepareStaticPrefetch({buildDirectory:directory}),/PREFETCH_ROUTE_NOT_STATIC: \/papers/);
});
